### ISSUE TITLE
Merge latest version from three.js

### ISSUE THREAD

**Issue by devingfx** [mrdoob/ui.js#3]
three.js editor's version of UI.js is earlier than this repo, if you get back the latest diffs in this repo, people (me 😅) will be able to contribute to this lib separately...

So the enderlaying question is: do you want to continue this lib as a standalone project?

**Comment by mrdoob** [comment]
https://github.com/mrdoob/ui.js/commit/9070faa20b9c575d63516c4a5e9ca0412f886d7a
